# Generated by Django 2.2.16 on 2022-08-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.ManyToManyField(related_name='film_rating', to='reviews.Review'),
        ),
    ]
